CREATE DATABASE QLkhach_san
USE QLkhach_san

--TAO BANG PHONG
CREATE TABLE PHONG
(MAPHONG INT PRIMARY KEY IDENTITY(1,1),
MAKS INT ,
DIENTICH FLOAT NULL ,
LOAI NVARCHAR(20) NULL ,
TANG INT NULL)

--TAO BANG KHACHSAN
CREATE TABLE KHACHSAN
(MAKS INT PRIMARY KEY IDENTITY(1,1) ,
TENKS NVARCHAR(50) NOT NULL,
DIACHI NVARCHAR(100) NULL,
DIENTICH FLOAT NULL,
TENGDKS NVARCHAR(50) NULL)

--TAO BANG NHATKYDATPHONG
CREATE TABLE NHATKYDATPHONG
(MADATPHONG INT ,
MAPHONG INT IDENTITY(1,1),
CHECKIN DATETIME NULL DEFAULT(GETDATE()),
CHECKOUT DATETIME NULL DEFAULT(GETDATE()),
SOLUONG INT NULL,
constraint fk primary key (MADATPHONG,MAPHONG))

--TAO RANG BUOC 
ALTER TABLE PHONG 
ADD CONSTRAINT FFF CHECK (LOAI IN ('PRO','VIP','GOLD')) 
--
ALTER TABLE PHONG ADD CONSTRAINT fk01 FOREIGN KEY(MAKS) REFERENCES KHACHSAN(MAKS)
--on delete cascade on update cascade on identity cascade 

ALTER TABLE NHATKYDATPHONG ADD CONSTRAINT fk02 FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG)
--ON delete cascade on update cascade

--NHAP DULIEU 
INSERT INTO PHONG (MAKS,DIENTICH,LOAI,TANG) VALUES(1,30,'PRO',2)
INSERT INTO PHONG (MAKS,DIENTICH,LOAI,TANG) VALUES(2,50,'VIP',2)
INSERT INTO PHONG (MAKS,DIENTICH,LOAI,TANG) VALUES(3,30,'PRO',3)
INSERT INTO PHONG (MAKS,DIENTICH,LOAI,TANG) VALUES(4,40,'VIP',4)
INSERT INTO PHONG (MAKS,DIENTICH,LOAI,TANG) VALUES(5,35,'GLOD',2)
SELECT*FROM PHONG


INSERT INTO KHACHSAN (TENKS,DIACHI,DIENTICH,TENGDKS) VALUES('HOA AN','33 LE CHIEU THING','322','AA')
INSERT INTO KHACHSAN (TENKS,DIACHI,DIENTICH,TENGDKS) VALUES('TRAN AM AN','THANG LONG','200','LONG')
INSERT INTO KHACHSAN (TENKS,DIACHI,DIENTICH,TENGDKS) VALUES('VINH HA LONG','MX CHAU','500','TRAN HAO MON')
INSERT INTO KHACHSAN (TENKS,DIACHI,DIENTICH,TENGDKS) VALUES('HOA MAT','700 LE ','300','ABC')
INSERT INTO KHACHSAN (TENKS,DIACHI,DIENTICH,TENGDKS) VALUES('HOANG LONG','HOAI NHON','400','SOFT')
SELECT *FROM KHACHSAN

INSERT INTO NHATKYDATPHONG (MADATPHONG,MAPHONG,SOLUONG) VALUES(1,1,34)
INSERT INTO NHATKYDATPHONG (MADATPHONG,MAPHONG,SOLUONG) VALUES(2,2,50)
INSERT INTO NHATKYDATPHONG (MADATPHONG,MAPHONG,SOLUONG) VALUES(3,3,20)
INSERT INTO NHATKYDATPHONG (MADATPHONG,MAPHONG,SOLUONG) VALUES(4,4,30)
INSERT INTO NHATKYDATPHONG (MADATPHONG,MAPHONG,SOLUONG) VALUES(5,4,30)
SELECT *FROM NHATKYDATPHONG

--PHAN 2
--1
SELECT MAPHONG 
FROM PHONG
WHERE DIENTICH > 40
--2 phong nao chua co khách đặt
SELECT MAPHONG
FROM NHATKYDATPHONG
WHERE MAPHONG not in (select maphong from phong)
--3
SELECT *FROM NHATKYDATPHONG
WHERE CHECKIN>='2022/7/19' 
AND CHECKOUT<='2022/9/20'
--44. Tính tiền phòng số 3: biết 1 ngày 300.000đ, check out sau 12h thì tính 1 ngày
SELECT CASE 
WHEN  DATEPART(HOUR,CHECKOUT) < 12 THEN DATEDIFF(DAY,CHECKIN,CHECKOUT)
ELSE DATEDIFF(DAY,CHECKIN,CHECKOUT) +1 
END *300000 AS N'TIỀN PHÒNG'
FROM NHATKYDATPHONG
WHERE MAPHONG=3
--5
SELECT MAKS, COUNT(MAPHONG)
FROM PHONG 
GROUP BY MAKS

--6
SELECT TENKS
FROM KHACHSAN
WHERE DIENTICH = (SELECT MAX(DIENTICH) FROM KHACHSAN)
--7
UPDATE NHATKYDATPHONG
SET checkin = '2021-07-16 19:00:00'
WHERE checkin = '2021-07-16 18:00:00'
--PHAN 3
--1Viết thủ tục để hủy thông tin đặt phòng của mã đặt phòng k nào đó (k là tham số của thủ tục)
CREATE PROCEDURE BAI1
    @K INT
AS
BEGIN
    DELETE FROM NHATKYDATPHONG
	WHERE MADATPHONG=@K
END

exec BAI1 
--2 Viết hàm trả lại số lượng phòng đã đặt trong ngày x (x là ngày/tháng/năm-tham số của hàm)
CREATE FUNCTION BAI2 (@ngay DATETIME)
RETURNS INT
AS
BEGIN
    DECLARE @soluong INT;
    SELECT @soluong = COUNT(*)
    FROM NHATKYDATPHONG
    WHERE CONVERT(DATE,checkin) = CONVERT(DATE,@ngay)

    RETURN @soluong
END



--Phần 4. Viết trigger checkin, checkout cùng ngày cùng giờ. Nghĩa là khi nhập vào bảng
--nhatkydatphong không cho phép trường checkin, chekout cùng giá trị.
CREATE TRIGGER BB1
ON NHATKYDATPHONG
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted WHERE checkin = checkout)
    BEGIN
        PRINT('KO NHAP DUOC VI CUNG GIA TRI')
        ROLLBACK TRAN
    END
END

--so luong phong checkin ngay hom nay 
select count(maphong)
from NHATKYDATPHONG
where CHECKIN=cast(getdate() as date)

--co bao nhieu phong thuoc loai 'PRO'
select count(maphong)
from phong 
where LOAI='pro'

--thong ke so luong phong theo tang 
select tang,count(maphong)
from PHONG
group by tang 

--ngay checkin nao co so luong nguoi dat phong la nhieu nhat 
select top 1 checkin 
from NHATKYDATPHONG
group by checkin
order by count(maphong) desc
--Cột 'NHATKYDATPHONG. CHECKIN' không hợp lệ trong danh sách chọn vì nó không được chứa 
--trong hàm tổng hợp hoặc mệnh đề GROUP BY. 


--23.Viết trigger tự động cập nhật TinhTrang OFF thành ON mỗi khi phòng đó có người
--đặt. Nghĩa là khi nhập vào bảng nhatkydatphong thì cập nhật OFF thành ON (mã phòng tương ứng).
create trigger bai23 
on nhatkydatphong 
after insert 
as begin 
        update NHATKYDATPHONG
		set tinhtrang='on' from inserted
		where inserted.maphong=NHATKYDATPHONG.maphong 
		and tinhtrang='off'
end 